title: "Blog about Software Development"
email: sashashpota@gmail.com
author:
  name: Sasha Shpota
  twitter: sashashpota
description: >
  Sasha Shpota blogging about Software Development, Java, Kotlin, IntelliJ Plugin Development, Front End and more.
baseurl: ""
url: "https://shpota.com"
copyright: "© Oleksandr Shpota, 2017—2021"
encoding: utf-8

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - Rakefile

minima:
  date_format: "%-d %b %Y"
